#!/bin/bash

cd $(dirname $0)
echo "!============URXVT===========" > ./Xresources
sed -e 's/^/urxvt./' urxvt/X >> ./Xresources

echo "!============COLROS==========" >> ./Xresources
cat ./colors >> ./Xresources

echo "Generated"
xrdb -merge ./Xresources
