#!/bin/bash

cur=`light -G`
cur=${cur%.*}

input=$1

if [[  ${input:0:1} == '+' || ${input:0:1} == '-' ]]
then
    end=`echo $cur$input | bc`
else
    end=$input
fi

cur=$((cur+1))
end=$(( end < 1 ? 1 : end ))
ebd=$(( end > 100 ? 100 : end ))
echo $end $cur

if [[ cur != end ]]
then
    for i in $(eval echo {$cur..$end})
    do
        light -S $i
        sleep 0.01
    done
fi
